import { motion } from "framer-motion"; // Import Framer Motion
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import MeditationComponent from "@/components/Meditation";

const Meditate = () => {
  // Animation variants for the container (stagger children)
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.25, // Slightly longer stagger for a meditative pace
      },
    },
  };

  // Variants for individual elements
  const textVariants = {
    hidden: { opacity: 0, y: -20 }, // Downward drift (from above)
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.7, ease: "easeInOut" }, // Smoother easing for calm
    },
  };

  const descriptionVariants = {
    hidden: { opacity: 0, y: 30 }, // Upward rise (from below)
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.9, ease: "easeInOut", delay: 0.25 },
    },
  };

  const componentVariants = {
    hidden: { opacity: 0, scale: 0.97 }, // Subtle scale for grounding
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        duration: 0.8,
        ease: "easeInOut",
        delay: 0.5,
        type: "spring",
        stiffness: 80, // Soft spring for a relaxed feel
      },
    },
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-1 bloom-container py-8">
        <motion.div
          className="space-y-8"
          variants={containerVariants}
          initial="hidden"
          animate="visible"
        >
          <div className="text-center">
            <motion.h1
              className="text-3xl font-bold mb-4 text-gradient mt-3 leading-tight uppercase tracking-wider font-montserrat"
              variants={textVariants}
            >
              Guided Meditation
            </motion.h1>
            <motion.p
              className="text-foreground/80 max-w-2xl mx-auto"
              variants={descriptionVariants}
            >
              Experience personalized meditation sessions generated by AI to address your specific emotional needs.
            </motion.p>
          </div>
          
          <motion.div variants={componentVariants}>
            <MeditationComponent />
          </motion.div>
        </motion.div>
      </main>
      
      <Footer />
    </div>
  );
};

export default Meditate;